server:
  port: 8080

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: instant-payment
    version: 1.0.0
    description: API for instant money transfers

logging:
  level:
    hu.bergerdenes.instantpayment: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instantpayments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092

# Resilience4j configuration
resilience4j:
  retry:
    instances:
      paymentService:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        sliding-window-size: 5

# SpringDoc OpenAPI config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# custom configuration
kafka:
  enabled: true
  server: kafka

